# -*- coding: utf-8 -*-
"""Ethos data preparation

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uep7rJLoW7e6QGrDqVvT5R8oL5p6pfi3
"""

import numpy as np
import pandas as pd

!pip install -U sentence-transformers

from sentence_transformers import SentenceTransformer, util
import torch

df_full_data=pd.read_csv("https://bl.iro.bl.uk/downloads/844ddfb8-122f-4df3-ac47-fb663bb6b31b?locale=en", encoding = "ISO-8859-1", engine="pyarrow")

# add additional columns for the abstract and Ethos id
df_full_data['Abstract_full']=df_full_data['Abstract'].apply(lambda x: x.decode('ISO-8859-1'))
df_full_data['Ethos_id']=df['EThOS URL'].apply(lambda x: x.split('.')[-1])

# save the data for future use
df_full_data.to_pickle("ethos_data.pkl")

# prepare and save title embeddings
embedder.max_seq_length=2048
title_embeddings = embedder.encode(df_full_data['Title'], convert_to_tensor=True)
torch.save(title_embeddings, 'title_embeddings(msmarco-distilbert-base-v4).pt')

# prepare and save abstract embeddings
abs_emb=embedder.encode(abstracts, convert_to_tensor=True, )
torch.save(abs_emb, 'abstract_embeddings(msmarco-distilbert-base-v4).pt')